Use locks to avoid multiple calls to code:get_object_code for the same fun
rabbitmq/khepri pull request #130
Opened 2022-08-15 14:50 UTC by dcorbacho

Parallel calls to a function that is not yet in the cache will call simultaneously `code:get_object_code/1`. This call then becomes very slow and then the cache update also happens in parallel, with the same value. 
Ensuring that only one process tries to process the function and update the cache yields much faster parallel execution times, while the other process then also hit the new cache value and not the processing function path.

2022-08-16 19:51 UTC, lukebakken reviewed
Is this a good place to use `try ... after`?
```
to_standalone_fun2_with_retry(Fun, State) ->
    case to_standalone_fun2(Fun, State) of
        undefined ->
            Lock = {{khepri_fun, Fun}, self()},
            try
                global:set_lock(Lock, [node()]),
                case to_standalone_fun2(Fun, State) of
                    undefined ->
                        to_standalone_fun3(Fun, State);
                    Other ->
                        Other
                end
            after
                global:del_lock(Lock, [node()])
            end;
        Other ->
            Other
    end.
```

2022-08-17 11:54 UTC, the-mikedavis approved these changes

2022-08-17 13:05 UTC, lukebakken approved these changes
Nice fix @dcorbacho!

2022-08-18 13:36 UTC, dumbbell requested changes
Could you please add a comment in the code to explain why we need a lock?

I think you can squash all commits into one and repeat the same explanation in the commit message.

2022-08-18 13:36 UTC, dumbbell commented on src/khepri_fun.erl
> +-spec to_standalone_fun2(Fun, State) -> {StandaloneFun, State} | undefined when
Could you please rename this function to `to_standalone_fun2_locked()` and call the new function `to_standalone_fun2()`?

This is a common convention so we understand that `to_standalone_fun2()` and `to_standalone_fun2_locked()` are the same thing, and `to_standalone_fun2()` is responsible for wrapping the call to `to_standalone_fun2_locked()` in a lock.

2022-08-18 13:36 UTC, dumbbell commented on src/khepri_fun.erl
> +to_standalone_fun2_with_retry(Fun, State) ->
Could you please move this function before `to_standalone_fun2_locked()` (instead of after)?

2022-08-18 13:36 UTC, dumbbell commented on src/khepri_fun.erl
> +                global:set_lock(Lock, [node()]),
The lock must be acquired before the try/catch because if this call raises an exception, `global:del_lock()` will be called despite no acquired lock.

2022-08-18 13:36 UTC, dumbbell commented on src/khepri_fun.erl
> +            Other
Could you please name the variable `StandaloneFunAndState` for instance? I feel like `Other` could be any random garbage returned by the function, but we always expect a success return value.

2022-08-18 16:37 UTC, dumbbell approved these changes

2022-08-18 16:38 UTC, dumbbell commented
I changed my mind w.r.t to the `_locked` suffix as I didn't read the patch correctly first, sorry.

I made a few cosmetic changes and will merge your pull request once CI is done.

Thank you!

2022-08-18 16:44 UTC, merged