mix: Add application definition
rabbitmq/khepri pull request #146
Opened 2022-10-04 01:03 UTC by the-mikedavis

Prior to this change, the Khepri application (`khepri_app`) was not started when running Khepri with Mix, for example with `iex -S mix`. Transaction functions created in IEx would fail since the persistent term `{khepri,skipped_modules_in_code_collection}` was undefined.

This change adds the `application/0` function suggested in the [`mix compile.app`](https://hexdocs.pm/mix/1.14.0/Mix.Tasks.Compile.App.html) documentation. The Erlang `app.src` file already provides the `applications`, `mod` and `env` options necessary to start the Khepri application, so we inherit the values directly from there.

2022-10-04 08:21 UTC, dumbbell commented
> Prior to this change, the Khepri application (`khepri_app`) was not started when running Khepri with Mix, for example with `iex -S mix`. Transaction functions created in IEx would fail since the persistent term `{khepri,skipped_modules_in_code_collection}` was undefined.

I can't reproduce the problem locally.

```
► iex -S mix
Erlang/OTP 25 [erts-13.0.4] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit:ns] [dtrace] [sharing-preserving]

===> Analyzing applications...
===> Compiling gen_batch_server
src/gen_batch_server.erl:269: Warning: INFO: receive matches any message, this is always fast
src/gen_batch_server.erl:323: Warning: INFO: receive matches any message, this is always fast

===> Analyzing applications...
===> Compiling seshat
===> Analyzing applications...
===> Compiling aten
===> Analyzing applications...
===> Compiling ra
Compiling 14 files (.erl)
Generated khepri app
Interactive Elixir (1.13.4) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> :application.which_applications() 
[
  {:khepri, 'Tree-like replicated on-disk database library', '0.4.3'},
  {:ra, 'Raft library', '2.1.0'},
  {:seshat, 'Counters registry', '0.3.2'},
  {:gen_batch_server, 'Generic batching server', '0.8.8'},
  {:aten, 'Erlang node failure detector', '0.5.8'},
  {:sasl, 'SASL  CXC 138 11', '4.2'},
  {:hex, 'hex', '1.0.1'},
  {:inets, 'INETS  CXC 138 49', '8.0'},
  {:ssl, 'Erlang/OTP SSL application', '10.8.3'},
  {:public_key, 'Public key infrastructure', '1.13'},
  {:asn1, 'The Erlang ASN1 compiler version 5.0.19', '5.0.19'},
  {:crypto, 'CRYPTO', '5.1.1'},
  {:mix, 'mix', '1.13.4'},
  {:iex, 'iex', '1.13.4'},
  {:elixir, 'elixir', '1.13.4'},
  {:compiler, 'ERTS  CXC 138 10', '8.2'},
  {:stdlib, 'ERTS  CXC 138 10', '4.0.1'},
  {:kernel, 'ERTS  CXC 138 10', '8.4.2'}
]
iex(2)> :khepri.info()
No stores running
:ok
iex(3)> :khepri.start()
{:ok, :khepri}
iex(4)> :khepri.info() 
Running stores:
  khepri
:ok
iex(5)> :khepri.info(:khepri)

== CLUSTER MEMBERS ==

nonode@nohost

== TREE ==

●
:ok
iex(6)> :khepri.transaction(fn () -> :ok end)
{:atomic, :ok}
```

Could this depend on the version of Elixir? I'm using Elixir 1.13.4.

2022-10-04 12:53 UTC, the-mikedavis commented
Ah, it looks like the transaction function needs to contain a function call:

```
iex> :khepri.transaction(fn -> :khepri_tx.abort(:foo) end)
** (ArgumentError) errors were found at the given arguments:

  * 1st argument: no persistent term stored with this key

    :persistent_term.get({:khepri, :skipped_modules_in_code_collection})
    (khepri 0.4.3) src/khepri_utils.erl:207: :khepri_utils.should_collect_code_for_module/1
    (khepri 0.4.3) src/khepri_tx.erl:642: :khepri_tx.should_process_function/4
    (khepri 0.4.3) src/khepri_fun.erl:2031: :khepri_fun.should_process_function/5
    (khepri 0.4.3) src/khepri_fun.erl:1487: :khepri_fun.pass1_process_call/4
    (khepri 0.4.3) src/khepri_fun.erl:1199: :khepri_fun.pass1_process_instructions/3
    (khepri 0.4.3) src/khepri_fun.erl:995: :khepri_fun.pass1_process_function_code/2
    (khepri 0.4.3) src/khepri_fun.erl:965: :khepri_fun.pass1_process_function/4
```

in order to hit the `khepri_fun:pass1_process_call/4` code.

I am also on 1.13.4 but with OTP24.

2022-10-06 07:19 UTC, dumbbell requested changes
I understand the problem now. I misread your pull request description and commit message.

For me, the application was started without this change. However, it is not initialized using `khepri_app:start/2`. That's the part I missed!

Here are some comments:
1. Could you please clarify that in the commit message? The notion of "application started" is too vague in this context.
2. Could you please also include `registered` in the filtered properties?

2022-10-11 09:02 UTC, dumbbell approved these changes
Thank you!

2022-10-11 09:02 UTC, merged